apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-base.fullname" . }}

data:
  application.yml: |
    server:
      shutdown: graceful
    spring:
      webflux:
        base-path: /api
    logging:
      level:
        root: INFO

  {{- with .Values.spring.application.yml }}
  application-{{.Values.spring.profile}}.yml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}