{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "spring-base.fullname" . }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`) && PathPrefix(`{{ .Values.ingress.pathPrefix }}`)
      kind: Rule
      services:
        - name: {{ include "spring-base.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}