{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "flutter-base.fullname" . }}
spec:
  entryPoints:
    - {{ cond "websecure" "web" .Values.ingress.https }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "flutter-base.fullname" . }}
          port: {{ .Values.service.port }}
 {{- if .Values.ingress.https }}
  tls:
    certResolver: {{ default "default" .Values.ingress.certResolver }}
 {{- end }}
{{- end }}